### ISSUE TITLE
routine options not available on new rust aspeak?

### ISSUE THREAD

**Issue by w-tim** [kxxt/aspeak#45]
Hi,

I like aspeak. After using it for one whole day, I received "AssertionError" issue now. Seems blocked by MSFT?

Checked this subject from closed issues and found that you are rebuilding one new rust edition.
Downloaded latest 4.0 beta 1 and found "-f" option and "-o" "--mp3" not working and seems not supported?
Changed the option name or cancelled these option?

My Environment is on intel mbp (MacOs 12.6.3 Montery), python 3.11.2.
I downed aspeak-x86_64-apple-darwin.

**Comment by kxxt** [comment]
The command line interface has been slightly changed in v4.0.0. Run `aspeak help` to learn how to use it.

Note that v4.0 is still unstable so the command line interface might be changed again before stable release.

> Downloaded latest 4.0 beta 1 and found "-f" option and "-o" "--mp3" not working and seems not supported?

A typical example would be `aspeak text -f input.txt -o xxx.mp3 -c mp3 -v en-US-JennyNeural`

> My Environment is on intel mbp (MacOs 12.6.3 Montery), python 3.11.2.

Actually, aspeak v4 doesn't need python anymore because it is rewritten in rust.
