### ISSUE TITLE
the free version may refer to this page：https://speech.microsoft.com/audiocontentcreation

### ISSUE THREAD

**Issue by ganjunhong** [kxxt/aspeak#65]

**Comment by kxxt** [comment]
This API is quite different than the azure tts API and aspeak won't add support for it.

FYI, if you want to continue to use aspeak for free, you can try to figure out how to use the edge tts endpoint(https://github.com/kxxt/aspeak/issues/56#issue-1640328594) . But `aspeak` won't use edge tts as the default trial endpoint because the feature set is quite limited and it involves stealing trusted client token.

**Comment by flt6** [comment]
Anyway, API at https://speech.microsoft.com/audiocontentcreation is strictly restricted too. which I have made a demo and found it.
(You can try it with aspeak in branch [alt-impl](https://github.com/kxxt/aspeak/tree/alt-impl))
